import type {
  Apparatus,
  AppData,
  BodyArea,
  Exercise,
  Level,
  MovementType,
  SpecialCondition,
  StartPosition,
} from "../types";

export const EXERCISE_CATALOG_VERSION = 2;

const SOURCES = {
  reformer: "https://contrologycohort.com/pilates-reformer-order/",
  reformerSupplement:
    "https://s3.amazonaws.com/kajabi-storefronts-production/file-uploads/sites/2147566588/themes/2150498899/downloads/70caaf-55c2-3478-3166-1b77ce8424ef_Exercise_Lists_2025_Reformer_Exercises.pdf",
  cadillac:
    "https://s3.amazonaws.com/s3.pilates.com/resources/instructions/400-346_CE-Manual-Trap_0519.pdf",
  cadillacSupplement:
    "https://www.birminghampilatesstudios.com/courses/trapeze-table/lessons/trapeze-table-exercise-list/",
  chair:
    "https://pilatesology.com/wp-content/uploads/2025/03/Wunda-Chair-Classical-Exercises-Order.pdf",
  barrel:
    "https://pilatesology.com/wp-content/uploads/2022/01/Classical-Ladder-Barrel-Exercises.pdf",
  annabel: "https://www.instagram.com/wellnessbyannabel/",
} as const;

const ANNABEL_REELS = {
  longBoxKneeling:
    "https://www.instagram.com/wellnessbyannabel/reel/Db8Zpr8Ooef/",
  lightSpringArms:
    "https://www.instagram.com/wellnessbyannabel/reel/Db3Nu5cO-cS/",
  quadrupedLegLift:
    "https://www.instagram.com/wellnessbyannabel/reel/Dbuz1hduNAe/",
  fixedBoxBridge:
    "https://www.instagram.com/wellnessbyannabel/reel/DbqYFunumqa/",
  gluteBoxFlow: "https://www.instagram.com/wellnessbyannabel/reel/DblPCQAujin/",
  stabilityArms:
    "https://www.instagram.com/wellnessbyannabel/reel/Dba723cuYpC/",
  longBoxLegStrap:
    "https://www.instagram.com/wellnessbyannabel/reel/DbP7_NFOs3W/",
  ballFlow: "https://www.instagram.com/wellnessbyannabel/reel/DbLJ8quOJCG/",
} as const;

const ANNABEL_NOTE =
  "靈感來源為 @wellnessbyannabel 公開 Reel；採描述性名稱方便備課，不代表原作者正式命名或唯一教學標準。";

const VIDEOS = {
  footwork:
    "https://www.pilatesanytime.com/exercise-view/6214/video/Pilates-Footwork-by-Amy-Havens",
  longStretch:
    "https://www.pilatesanytime.com/exercise-view/5675/video/Pilates-Long-Stretch-Series-by-Lesley-Logan",
  pushThrough:
    "https://www.pilatesanytime.com/workshop-view/3404/video/Pilates-Push-Through-Bar-by-Benjamin-Degenhardt",
  legSprings:
    "https://www.pilatesanytime.com/workshop-view/3406/video/Pilates-Leg-Springs-by-Benjamin-Degenhardt",
  chairFundamentals:
    "https://www.pilatesanytime.com/class-view/1645/video/Pilates-Wunda-Chair-Fundamentals-by-Meredith-Rogers",
  chairTraditional:
    "https://www.pilatesanytime.com/class-view/696/video/Pilates-Traditional-Wunda-Chair-by-Brett-Howard",
  barrel:
    "https://www.pilatesanytime.com/class-view/6079/video/Pilates-Classical-Ladder-Barrel-by-Lesley-Logan",
} as const;

type Seed = {
  id: string;
  nameZh: string;
  nameEn: string;
  apparatus: Apparatus;
  level: Level;
  areas: BodyArea[];
  positions: StartPosition[];
  movementType?: MovementType;
  reps?: string;
  seconds?: number;
  usesBox?: boolean;
  conditions?: SpecialCondition[];
  aliases?: string[];
  spring?: string;
  footbar?: string;
  headrest?: string;
  descriptionFlow?: string;
  cueMovement?: string;
  regression?: string;
  progression?: string;
  personalNote?: string;
  sourceUrl: string;
  demoVideoUrl?: string;
};

const R = (
  id: string,
  nameZh: string,
  nameEn: string,
  level: Level,
  areas: BodyArea[],
  positions: StartPosition[],
  extra: Partial<
    Omit<
      Seed,
      "id" | "nameZh" | "nameEn" | "level" | "areas" | "positions" | "apparatus"
    >
  > = {},
): Seed => ({
  id,
  nameZh,
  nameEn,
  apparatus: "Reformer",
  level,
  areas,
  positions,
  sourceUrl: SOURCES.reformer,
  ...extra,
});

const C = (
  id: string,
  nameZh: string,
  nameEn: string,
  level: Level,
  areas: BodyArea[],
  positions: StartPosition[],
  extra: Partial<
    Omit<
      Seed,
      "id" | "nameZh" | "nameEn" | "level" | "areas" | "positions" | "apparatus"
    >
  > = {},
): Seed => ({
  id,
  nameZh,
  nameEn,
  apparatus: "Cadillac",
  level,
  areas,
  positions,
  sourceUrl: SOURCES.cadillac,
  ...extra,
});

const W = (
  id: string,
  nameZh: string,
  nameEn: string,
  level: Level,
  areas: BodyArea[],
  positions: StartPosition[],
  extra: Partial<
    Omit<
      Seed,
      "id" | "nameZh" | "nameEn" | "level" | "areas" | "positions" | "apparatus"
    >
  > = {},
): Seed => ({
  id,
  nameZh,
  nameEn,
  apparatus: "Chair",
  level,
  areas,
  positions,
  sourceUrl: SOURCES.chair,
  ...extra,
});

const B = (
  id: string,
  nameZh: string,
  nameEn: string,
  level: Level,
  areas: BodyArea[],
  positions: StartPosition[],
  extra: Partial<
    Omit<
      Seed,
      "id" | "nameZh" | "nameEn" | "level" | "areas" | "positions" | "apparatus"
    >
  > = {},
): Seed => ({
  id,
  nameZh,
  nameEn,
  apparatus: "Barrel",
  level,
  areas,
  positions,
  sourceUrl: SOURCES.barrel,
  demoVideoUrl: VIDEOS.barrel,
  ...extra,
});

const reformerSeeds: Seed[] = [
  R(
    "demo-footwork",
    "腳踩踏板",
    "Footwork",
    "初階",
    ["大腿", "臀部", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.footwork },
  ),
  R(
    "demo-bridge",
    "肩橋",
    "Bridge",
    "初階",
    ["臀部", "大腿", "核心"],
    ["仰躺"],
  ),
  R(
    "demo-hundred-prep",
    "百次預備",
    "Hundred Prep",
    "初階",
    ["核心", "胸部"],
    ["仰躺"],
  ),
  R(
    "demo-feet-straps",
    "腳套系列",
    "Feet in Straps",
    "初中階",
    ["髖部", "大腿", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  R("demo-frog", "青蛙", "Frog", "初中階", ["大腿", "髖部", "核心"], ["仰躺"]),
  R(
    "demo-leg-circle",
    "腿部畫圈",
    "Leg Circles",
    "初中階",
    ["髖部", "核心"],
    ["仰躺"],
  ),
  R(
    "demo-short-spine",
    "短脊柱按摩",
    "Short Spine Massage",
    "中階",
    ["核心", "背部", "髖部"],
    ["仰躺"],
    { conditions: ["頸椎負荷"] },
  ),
  R(
    "demo-elephant",
    "大象",
    "Elephant",
    "初中階",
    ["大腿", "背部", "核心"],
    ["站姿"],
    { demoVideoUrl: VIDEOS.longStretch },
  ),
  R(
    "demo-long-stretch",
    "長伸展",
    "Long Stretch",
    "中階",
    ["核心", "肩膀", "手臂"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"], demoVideoUrl: VIDEOS.longStretch },
  ),
  R(
    "demo-knee-stretch",
    "跪姿收膝系列",
    "Knee Stretch Series",
    "初中階",
    ["核心", "大腿"],
    ["跪姿"],
    { conditions: ["手腕負重", "膝蓋負重"] },
  ),
  R(
    "demo-scooter",
    "滑板車",
    "Scooter",
    "中階",
    ["臀部", "大腿", "髖部"],
    ["站姿"],
    { conditions: ["單腳", "單側", "平衡需求"] },
  ),
  R(
    "demo-mermaid",
    "美人魚",
    "Mermaid",
    "初中階",
    ["髖部", "背部", "伸展"],
    ["坐姿"],
  ),
  R(
    "demo-eves-lunge",
    "伊芙弓箭步",
    "Eve's Lunge",
    "中階",
    ["髖部", "大腿", "伸展"],
    ["跪姿"],
    { conditions: ["單側", "膝蓋負重"] },
  ),
  R(
    "catalog-ref-footwork-toes",
    "腳掌踩踏",
    "Footwork: Toes",
    "初階",
    ["大腿", "小腿", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.footwork },
  ),
  R(
    "catalog-ref-footwork-arches",
    "足弓踩踏",
    "Footwork: Arches",
    "初階",
    ["大腿", "小腿", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.footwork },
  ),
  R(
    "catalog-ref-footwork-heels",
    "腳跟踩踏",
    "Footwork: Heels",
    "初階",
    ["大腿", "臀部", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.footwork },
  ),
  R(
    "catalog-ref-footwork-tendon",
    "腳踝升降",
    "Footwork: Tendon Stretch",
    "初階",
    ["小腿", "大腿", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.footwork },
  ),
  R(
    "catalog-ref-hundred",
    "百次",
    "Hundred",
    "中階",
    ["核心", "手臂", "胸部"],
    ["仰躺"],
  ),
  R(
    "catalog-ref-overhead",
    "過頭捲舉",
    "Overhead",
    "中高階",
    ["核心", "背部", "髖部"],
    ["仰躺"],
    { conditions: ["頸椎負荷"] },
  ),
  R(
    "catalog-ref-coordination",
    "協調",
    "Coordination",
    "中階",
    ["核心", "手臂", "大腿"],
    ["仰躺"],
  ),
  R(
    "catalog-ref-rowing-round",
    "划船－圓背",
    "Rowing: Round",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-rowing-tall",
    "划船－高坐",
    "Rowing: Tall",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-rowing-shoulders",
    "划船－肩膀",
    "Rowing: Shoulders",
    "中階",
    ["肩膀", "手臂", "背部"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-rowing-hips",
    "划船－髖部",
    "Rowing: Hips",
    "中階",
    ["背部", "手臂", "核心"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-rowing-shave",
    "刮鬍式",
    "Rowing: Shave",
    "中階",
    ["肩膀", "手臂", "核心"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-rowing-hug",
    "擁抱式",
    "Rowing: Hug",
    "中階",
    ["胸部", "肩膀", "手臂"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-longbox-swan",
    "長箱天鵝",
    "Long Box: Swan",
    "中階",
    ["背部", "臀部", "全身"],
    ["趴姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-pull-straps",
    "拉繩",
    "Long Box: Pull Straps",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["趴姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-t-pull",
    "T 字拉繩",
    "Long Box: T Pull",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["趴姿"],
    { usesBox: true, sourceUrl: SOURCES.reformerSupplement },
  ),
  R(
    "catalog-ref-backstroke",
    "仰泳式",
    "Long Box: Backstroke",
    "中階",
    ["核心", "手臂", "大腿"],
    ["仰躺"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-longbox-teaser",
    "長箱 Teaser",
    "Long Box: Teaser",
    "中高階",
    ["核心", "髖部", "手臂"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-breaststroke",
    "蛙泳式",
    "Long Box: Breast Stroke",
    "中高階",
    ["背部", "肩膀", "全身"],
    ["趴姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-horseback",
    "騎馬式",
    "Long Box: Horseback",
    "中高階",
    ["核心", "大腿", "平衡"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-down-stretch",
    "下伸展",
    "Down Stretch",
    "中階",
    ["核心", "背部", "髖部"],
    ["跪姿"],
    { conditions: ["膝蓋負重"], demoVideoUrl: VIDEOS.longStretch },
  ),
  R(
    "catalog-ref-up-stretch",
    "上伸展",
    "Up Stretch",
    "中階",
    ["核心", "肩膀", "大腿"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"], demoVideoUrl: VIDEOS.longStretch },
  ),
  R(
    "catalog-ref-long-back-stretch",
    "長背伸展",
    "Long Back Stretch",
    "中高階",
    ["手臂", "肩膀", "核心"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"], demoVideoUrl: VIDEOS.longStretch },
  ),
  R(
    "catalog-ref-stomach-round",
    "胃部按摩－圓背",
    "Stomach Massage: Round",
    "中階",
    ["核心", "大腿", "髖部"],
    ["坐姿"],
  ),
  R(
    "catalog-ref-stomach-hands",
    "胃部按摩－手向後",
    "Stomach Massage: Hands Back",
    "中階",
    ["核心", "大腿", "背部"],
    ["坐姿"],
  ),
  R(
    "catalog-ref-stomach-reach",
    "胃部按摩－上舉",
    "Stomach Massage: Reaching",
    "中階",
    ["核心", "大腿", "肩膀"],
    ["坐姿"],
  ),
  R(
    "catalog-ref-stomach-twist",
    "胃部按摩－旋轉",
    "Stomach Massage: Twist",
    "中高階",
    ["核心", "背部", "大腿"],
    ["坐姿"],
  ),
  R(
    "catalog-ref-shortbox-round",
    "短箱－圓背",
    "Short Box: Round",
    "初中階",
    ["核心", "背部"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-shortbox-flat",
    "短箱－平背",
    "Short Box: Flat Back",
    "中階",
    ["核心", "背部", "穩定"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-shortbox-side",
    "短箱－側彎",
    "Short Box: Side to Side",
    "中階",
    ["核心", "背部", "伸展"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-shortbox-twist",
    "短箱－旋轉",
    "Short Box: Twist",
    "中階",
    ["核心", "背部", "穩定"],
    ["坐姿"],
    { usesBox: true },
  ),
  R(
    "catalog-ref-shortbox-tree",
    "短箱－爬樹",
    "Short Box: Tree",
    "中階",
    ["核心", "髖部", "伸展"],
    ["坐姿"],
    { usesBox: true, conditions: ["單腳", "單側"] },
  ),
  R(
    "catalog-ref-semicircle",
    "半圓",
    "Semi Circle",
    "中高階",
    ["臀部", "背部", "大腿"],
    ["仰躺"],
  ),
  R(
    "catalog-ref-chest-expansion",
    "擴胸",
    "Chest Expansion",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["跪姿"],
    { conditions: ["膝蓋負重"] },
  ),
  R(
    "catalog-ref-thigh-stretch",
    "大腿伸展",
    "Thigh Stretch",
    "中階",
    ["大腿", "核心", "伸展"],
    ["跪姿"],
    { conditions: ["膝蓋負重"] },
  ),
  R(
    "catalog-ref-snake-twist",
    "蛇式與旋轉",
    "Snake & Twist",
    "高階",
    ["全身", "核心", "肩膀"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重", "平衡需求"] },
  ),
  R(
    "catalog-ref-corkscrew",
    "開瓶器",
    "Corkscrew",
    "高階",
    ["核心", "背部", "髖部"],
    ["仰躺"],
    { conditions: ["頸椎負荷"] },
  ),
  R(
    "catalog-ref-balance-control",
    "離床平衡控制",
    "Balance Control Off",
    "高階",
    ["核心", "平衡", "全身"],
    ["仰躺"],
    { conditions: ["頸椎負荷", "平衡需求"] },
  ),
  R(
    "catalog-ref-long-spine",
    "長脊柱按摩",
    "Long Spine Massage",
    "中高階",
    ["核心", "背部", "髖部"],
    ["仰躺"],
    { conditions: ["頸椎負荷"] },
  ),
  R(
    "catalog-ref-running",
    "跑步",
    "Running",
    "初階",
    ["小腿", "大腿", "穩定"],
    ["仰躺"],
  ),
  R(
    "catalog-ref-pelvic-lift",
    "骨盆抬升",
    "Pelvic Lift",
    "初中階",
    ["臀部", "大腿", "核心"],
    ["仰躺"],
  ),
  R(
    "catalog-ref-side-split",
    "側劈腿",
    "Side Split",
    "中階",
    ["大腿", "髖部", "平衡"],
    ["站姿"],
    { conditions: ["平衡需求", "雙側"] },
  ),
  R(
    "catalog-ref-front-split",
    "前劈腿",
    "Front Split",
    "中高階",
    ["髖部", "大腿", "伸展"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"] },
  ),
  R(
    "catalog-ref-russian-split",
    "俄式劈腿",
    "Russian Split",
    "高階",
    ["髖部", "大腿", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"] },
  ),
  R(
    "catalog-ref-knee-round",
    "跪姿收膝－圓背",
    "Knee Stretch: Round",
    "初中階",
    ["核心", "大腿", "肩膀"],
    ["跪姿"],
    { conditions: ["手腕負重", "膝蓋負重"] },
  ),
  R(
    "catalog-ref-knee-arched",
    "跪姿收膝－拱背",
    "Knee Stretch: Arched",
    "中階",
    ["核心", "背部", "大腿"],
    ["跪姿"],
    { conditions: ["手腕負重", "膝蓋負重"] },
  ),
  R(
    "catalog-ref-knees-off",
    "跪姿收膝－膝離床",
    "Knee Stretch: Knees Off",
    "中高階",
    ["核心", "大腿", "肩膀"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"] },
  ),
  R(
    "catalog-ref-annabel-longbox-tall-kneeling-overhead",
    "長箱高跪姿過頭拉繩（Annabel 變化）",
    "Long Box Tall-Kneeling Overhead Strap Press (Annabel Variation)",
    "中階",
    ["肩膀", "手臂", "核心"],
    ["跪姿"],
    {
      aliases: ["Long Box Kneeling Arms", "長箱跪姿手臂"],
      usesBox: true,
      conditions: ["膝蓋負重", "平衡需求"],
      descriptionFlow:
        "高跪於長箱並保持軀幹穩定，雙手持拉繩完成受控制的過頭手臂路徑。",
      cueMovement: "肋骨保持連結，手臂移動時避免腰椎代償或聳肩。",
      regression: "改為坐姿或坐在腳跟上，縮小過頭幅度並降低阻力。",
      progression: "維持高跪姿，加入停留、節奏或更長的手臂路徑。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.longBoxKneeling,
    },
  ),
  R(
    "catalog-ref-annabel-longbox-half-kneeling-arm-open",
    "長箱半跪姿單臂開展（Annabel 變化）",
    "Long Box Half-Kneeling Arm Open (Annabel Variation)",
    "中高階",
    ["肩膀", "手臂", "核心", "平衡"],
    ["跪姿"],
    {
      aliases: ["Half-Kneeling Arm Open", "Light Spring Arm Flow"],
      usesBox: true,
      conditions: ["膝蓋負重", "單側", "平衡需求"],
      spring: "原貼文使用輕彈簧；請依品牌與學員換算",
      descriptionFlow:
        "在長箱上採半跪姿，以單側拉繩搭配另一側手臂開展，維持骨盆與軀幹穩定。",
      cueMovement: "先固定骨盆，再讓手臂向側方展開；避免身體跟著拉繩旋轉。",
      regression: "拿掉手持輔具、改坐姿或增加支撐面。",
      progression: "在動作穩定後加入輕量輔具或更長的離心控制。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.lightSpringArms,
    },
  ),
  R(
    "catalog-ref-annabel-quadruped-headrest-leg-lift",
    "四足跪手扶頭枕單腿抬舉（Annabel 變化）",
    "Quadruped Leg Lift – Hands on Headrest (Annabel Variation)",
    "中階",
    ["臀部", "核心", "穩定"],
    ["四足跪姿"],
    {
      aliases: ["Quadruped Donkey Kick", "四足跪抬腿"],
      conditions: ["手腕負重", "肩膀負重", "膝蓋負重", "單側"],
      spring: "原貼文使用單一輕彈簧；請依品牌與學員換算",
      headrest: "作為手部支撐，先確認穩固",
      descriptionFlow:
        "雙手或前臂支撐頭枕，一膝跪在 Carriage，另一腿向後上方伸長並控制回來。",
      cueMovement: "保持骨盆朝下與肩胛穩定，抬腿來自髖部而不是腰椎擠壓。",
      regression: "先不移動 Carriage，只做小幅度腿部伸長或抬舉。",
      progression: "在骨盆穩定下加入 Carriage 滑動、脈衝或腿部路徑變化。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.quadrupedLegLift,
    },
  ),
  R(
    "catalog-ref-annabel-longbox-shoulder-bridge",
    "長箱肩背支撐橋式（Annabel 變化）",
    "Long Box Shoulder-Supported Bridge (Annabel Variation)",
    "中階",
    ["臀部", "大腿", "核心"],
    ["仰躺"],
    {
      aliases: ["Elevated Bridge on Long Box", "箱上橋式"],
      usesBox: true,
      conditions: ["雙腳"],
      footbar: "依腳部支撐位置調整或收起",
      descriptionFlow:
        "肩背由固定長箱支撐，雙腳踩在穩定支撐點，抬起與放下骨盆完成橋式。",
      cueMovement: "腳掌平均施力，讓骨盆由臀腿帶起，避免重量壓向頸部。",
      regression: "回到 Carriage 上的一般橋式，降低肩背高度。",
      progression: "在骨盆穩定後加入停留、脈衝或單腳預備。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.fixedBoxBridge,
    },
  ),
  R(
    "catalog-ref-annabel-box-assisted-scooter",
    "箱輔助分腿蹲滑行（Annabel 變化）",
    "Box-Assisted Split Squat / Scooter (Annabel Variation)",
    "中階",
    ["臀部", "大腿", "髖部", "平衡"],
    ["站姿"],
    {
      aliases: ["Box-Assisted Scooter", "Elevated Scooter"],
      usesBox: true,
      conditions: ["單腳", "單側", "平衡需求"],
      descriptionFlow:
        "一腳站在固定長箱，另一膝或腳由 Carriage 支撐，以分腿蹲姿控制 Carriage 滑動。",
      cueMovement: "前腳三點平均踩穩，骨盆保持朝前，去程與回程都由臀腿控制。",
      regression: "縮短滑動距離、移除手持輔具，並提供固定扶握。",
      progression: "加入手臂動作、停留或輕量輔具，但不犧牲骨盆穩定。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.gluteBoxFlow,
    },
  ),
  R(
    "catalog-ref-annabel-longbox-seated-goalpost",
    "長箱坐姿 Goalpost 手臂拉繩（Annabel 變化）",
    "Long Box Seated Goalpost Arm Press (Annabel Variation)",
    "中階",
    ["肩膀", "手臂", "背部", "核心"],
    ["坐姿"],
    {
      aliases: ["Seated Goalpost Arms", "長箱坐姿手臂"],
      usesBox: true,
      descriptionFlow:
        "坐在長箱上，雙手持拉繩並維持 Goalpost 手臂位置，控制手臂開合或上推。",
      cueMovement: "坐骨穩定、肋骨保持連結，手肘移動時肩膀遠離耳朵。",
      regression: "減少阻力與手臂高度，或先做單純肩胛控制。",
      progression: "加入軀幹穩定挑戰、節奏或單側手臂變化。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.stabilityArms,
    },
  ),
  R(
    "catalog-ref-annabel-longbox-quadruped-leg-strap",
    "長箱四足跪單腿腳套伸展（Annabel 變化）",
    "Long Box Quadruped Single-Leg Strap Extension (Annabel Variation)",
    "中高階",
    ["臀部", "核心", "髖部", "穩定"],
    ["四足跪姿"],
    {
      aliases: ["Quadruped Leg Strap", "長箱單腿腳套"],
      usesBox: true,
      conditions: ["手腕負重", "肩膀負重", "膝蓋負重", "單側"],
      descriptionFlow:
        "四足跪於長箱，單腳套入拉繩向後伸長，再控制髖部回到起始位置。",
      cueMovement: "支撐側肩胛與骨盆保持穩定，腿向後延伸而非把腰椎壓低。",
      regression: "先不使用腳套，練習徒手單腿伸長或縮小活動範圍。",
      progression: "在軀幹穩定後加入腿部高度、停留或小幅度脈衝。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.longBoxLegStrap,
    },
  ),
  R(
    "catalog-ref-annabel-box-ball-ab-curl",
    "箱上球輔助腹部捲曲（Annabel 變化）",
    "Box-Supported Abdominal Curl with Ball (Annabel Variation)",
    "初中階",
    ["核心", "穩定"],
    ["仰躺"],
    {
      aliases: ["Ab Curl with Ball", "箱上腹部捲曲"],
      usesBox: true,
      conditions: ["頸椎負荷"],
      descriptionFlow:
        "骨盆或腰背由箱與小球支撐，雙腿彎曲，完成小幅度胸椎屈曲與控制回程。",
      cueMovement: "視線朝膝蓋方向，胸骨向骨盆靠近；避免用手拉頭或甩動。",
      regression: "增加頭頸支撐、縮小捲曲幅度，或讓雙腳保持固定支撐。",
      progression: "維持軀幹控制後加入腿部變化、停留或手臂路徑。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.ballFlow,
    },
  ),
  R(
    "catalog-ref-annabel-box-split-squat-ball-reach",
    "箱輔助分腿蹲＋球夾手臂變化（Annabel 變化）",
    "Box-Assisted Split Squat with Ball & Arm Reach (Annabel Variation)",
    "中高階",
    ["臀部", "大腿", "核心", "平衡"],
    ["站姿"],
    {
      aliases: ["Split Squat Ball Flow", "箱輔助弓箭步"],
      usesBox: true,
      conditions: ["單腳", "單側", "平衡需求"],
      descriptionFlow:
        "以箱與 Carriage 建立分腿站姿，搭配小球夾持及單側手臂前伸或划動。",
      cueMovement: "先穩定下肢與骨盆，再加入手臂；Carriage 回程不可失去控制。",
      regression: "拿掉小球與手臂負重，提供扶握並縮短 Carriage 行程。",
      progression: "加入輕量輔具、手臂路徑或底部停留。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.ballFlow,
    },
  ),
  R(
    "catalog-ref-annabel-tall-kneeling-strap-ball-press",
    "高跪姿單臂拉繩＋球上舉（Annabel 變化）",
    "Tall-Kneeling Single-Arm Strap & Ball Press (Annabel Variation)",
    "中階",
    ["肩膀", "手臂", "核心", "穩定"],
    ["跪姿"],
    {
      aliases: ["Tall Kneeling Ball Press", "高跪姿球上舉"],
      conditions: ["膝蓋負重", "單側", "平衡需求"],
      descriptionFlow:
        "高跪於 Carriage，一手控制拉繩，雙手配合小球完成胸前至上方的推舉路徑。",
      cueMovement: "臀部保持啟動、肋骨不外翻，手臂移動時骨盆維持朝前。",
      regression: "改坐姿、拿掉小球，或以雙手對稱路徑練習。",
      progression: "加入單側停留、旋轉前置或更長的離心控制。",
      personalNote: ANNABEL_NOTE,
      sourceUrl: SOURCES.annabel,
      demoVideoUrl: ANNABEL_REELS.ballFlow,
    },
  ),
];

const cadillacSeeds: Seed[] = [
  C(
    "catalog-cad-roll-back",
    "後滾",
    "Roll Back",
    "初階",
    ["核心", "背部"],
    ["坐姿"],
  ),
  C(
    "catalog-cad-straight-arms",
    "手臂彈簧－直臂",
    "Arm Springs: Straight Arms",
    "初階",
    ["手臂", "肩膀", "背部"],
    ["仰躺"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-arm-circles",
    "手臂彈簧－畫圈",
    "Arm Springs: Circles",
    "初中階",
    ["肩膀", "手臂", "穩定"],
    ["仰躺"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-triceps",
    "手臂彈簧－三頭肌",
    "Arm Springs: Triceps",
    "初中階",
    ["手臂", "肩膀"],
    ["仰躺"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-leg-frog",
    "腿部彈簧－青蛙",
    "Leg Springs: Frog",
    "初階",
    ["髖部", "大腿", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-leg-circles",
    "腿部彈簧－畫圈",
    "Leg Springs: Circles",
    "初中階",
    ["髖部", "核心", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-leg-scissors",
    "腿部彈簧－剪刀",
    "Leg Springs: Scissors",
    "中階",
    ["髖部", "大腿", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-leg-beats",
    "腿部彈簧－拍腿",
    "Leg Springs: Beats",
    "中階",
    ["大腿", "臀部", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-leg-walking",
    "腿部彈簧－走路",
    "Leg Springs: Walking",
    "初中階",
    ["大腿", "髖部", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-leg-bicycle",
    "腿部彈簧－腳踏車",
    "Leg Springs: Bicycle",
    "中階",
    ["髖部", "大腿", "核心"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-circular-frog",
    "腿部彈簧－圓形青蛙",
    "Leg Springs: Circular Frog",
    "中階",
    ["髖部", "大腿", "穩定"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
  C(
    "catalog-cad-push-through",
    "推桿前伸",
    "Push Through",
    "初中階",
    ["背部", "核心", "伸展"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-teaser",
    "推桿 Teaser",
    "Push Through Bar: Teaser",
    "中高階",
    ["核心", "手臂", "髖部"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-reverse-push",
    "反向推桿",
    "Reverse Push Through",
    "中階",
    ["肩膀", "背部", "核心"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-sitting-press",
    "坐姿下壓",
    "Sitting Press Down",
    "中階",
    ["手臂", "肩膀", "核心"],
    ["坐姿"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-sitting-mermaid",
    "坐姿美人魚",
    "Sitting Mermaid",
    "初中階",
    ["背部", "髖部", "伸展"],
    ["坐姿"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-kneeling-press",
    "跪姿下壓",
    "Kneeling Press Down",
    "中階",
    ["手臂", "肩膀", "核心"],
    ["跪姿"],
    { conditions: ["膝蓋負重"], sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-kneeling-mermaid",
    "跪姿美人魚",
    "Kneeling Mermaid",
    "中階",
    ["背部", "核心", "伸展"],
    ["跪姿"],
    { conditions: ["膝蓋負重"], sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-swan",
    "推桿天鵝",
    "Push Through Bar: Swan",
    "中階",
    ["背部", "臀部", "肩膀"],
    ["趴姿"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-shoulder-roll",
    "肩橋滾動",
    "Shoulder Roll Down",
    "中階",
    ["背部", "臀部", "核心"],
    ["仰躺"],
  ),
  C(
    "catalog-cad-leg-pumps",
    "肩橋腿部下壓",
    "Shoulder Roll Down: Leg Pumps",
    "中階",
    ["臀部", "大腿", "核心"],
    ["仰躺"],
  ),
  C(
    "catalog-cad-spine-roll-up",
    "肩橋脊柱捲起",
    "Shoulder Roll Down: Spine Roll Up",
    "中高階",
    ["背部", "核心", "臀部"],
    ["仰躺"],
  ),
  C(
    "catalog-cad-monkey",
    "猴子式",
    "Monkey",
    "中階",
    ["背部", "大腿", "伸展"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-tower",
    "塔式",
    "Tower",
    "中高階",
    ["背部", "核心", "大腿"],
    ["仰躺"],
    { conditions: ["頸椎負荷"], demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-hip-stretch",
    "推桿髖部伸展",
    "Push Through Bar: Hip Stretch",
    "初中階",
    ["髖部", "大腿", "伸展"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.pushThrough },
  ),
  C(
    "catalog-cad-standing-chest",
    "站姿擴胸",
    "Standing Chest Expansion",
    "中階",
    ["背部", "肩膀", "手臂"],
    ["站姿"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-standing-side",
    "站姿側臂",
    "Standing Side Arms",
    "中階",
    ["肩膀", "手臂", "核心"],
    ["站姿"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-standing-squat",
    "站姿深蹲",
    "Standing Squats",
    "初中階",
    ["大腿", "臀部", "核心"],
    ["站姿"],
    { sourceUrl: SOURCES.cadillacSupplement },
  ),
  C(
    "catalog-cad-side-adductor",
    "側躺內收肌下拉",
    "Side-Lying Adductor Pull",
    "中階",
    ["大腿", "髖部", "核心"],
    ["側躺"],
    { conditions: ["單側"] },
  ),
  C(
    "catalog-cad-leg-lowers",
    "腿部彈簧下放",
    "Leg Spring Lowers",
    "初中階",
    ["核心", "髖部", "大腿"],
    ["仰躺"],
    { demoVideoUrl: VIDEOS.legSprings },
  ),
];

const chairSeeds: Seed[] = [
  W(
    "catalog-chair-footwork-toes",
    "椅上腳掌踩踏",
    "Chair Footwork: Toes",
    "初階",
    ["大腿", "小腿", "核心"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-footwork-arches",
    "椅上足弓踩踏",
    "Chair Footwork: Arches",
    "初階",
    ["大腿", "小腿", "穩定"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-footwork-heels",
    "椅上腳跟踩踏",
    "Chair Footwork: Heels",
    "初階",
    ["大腿", "臀部", "穩定"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-tendon",
    "椅上腳踝升降",
    "Chair Footwork: Tendon Stretch",
    "初中階",
    ["小腿", "大腿", "穩定"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-push-down",
    "站姿下壓",
    "Push Down",
    "初中階",
    ["核心", "背部", "肩膀"],
    ["站姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-swan",
    "椅上天鵝",
    "Swan",
    "中階",
    ["背部", "臀部", "肩膀"],
    ["趴姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-swan-one-arm",
    "單臂天鵝",
    "Swan One Arm",
    "中高階",
    ["背部", "肩膀", "核心"],
    ["趴姿"],
    { conditions: ["單側"] },
  ),
  W(
    "catalog-chair-teaser-top",
    "椅上 Teaser",
    "Teaser on Top",
    "中高階",
    ["核心", "髖部", "平衡"],
    ["坐姿"],
  ),
  W(
    "catalog-chair-mermaid-seated",
    "椅上坐姿美人魚",
    "Mermaid Seated",
    "初中階",
    ["背部", "髖部", "伸展"],
    ["坐姿"],
    { demoVideoUrl: VIDEOS.chairFundamentals },
  ),
  W(
    "catalog-chair-backward-arms",
    "反向手臂下壓",
    "Backward Arms",
    "中階",
    ["手臂", "肩膀", "背部"],
    ["坐姿"],
  ),
  W(
    "catalog-chair-arm-frog",
    "手臂青蛙",
    "Arm Frog",
    "中階",
    ["手臂", "肩膀", "核心"],
    ["跪姿"],
    { conditions: ["膝蓋負重"] },
  ),
  W(
    "catalog-chair-mermaid-kneeling",
    "跪姿美人魚",
    "Mermaid Kneeling",
    "中階",
    ["背部", "核心", "伸展"],
    ["跪姿"],
    { conditions: ["膝蓋負重"] },
  ),
  W(
    "catalog-chair-horseback",
    "椅上騎馬式",
    "Horseback",
    "中高階",
    ["核心", "大腿", "平衡"],
    ["坐姿"],
  ),
  W(
    "catalog-chair-push-up-bottom",
    "下方伏地挺身",
    "Push Up Bottom",
    "中高階",
    ["手臂", "肩膀", "核心"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"] },
  ),
  W(
    "catalog-chair-snake-twist",
    "椅上蛇式旋轉",
    "Snake Twist",
    "高階",
    ["全身", "核心", "肩膀"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "平衡需求"] },
  ),
  W(
    "catalog-chair-push-up-top",
    "椅上伏地挺身",
    "Push Up Top",
    "中高階",
    ["手臂", "肩膀", "核心"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"] },
  ),
  W(
    "catalog-chair-mountain-climb",
    "登山式",
    "Mountain Climb",
    "中高階",
    ["大腿", "臀部", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"], demoVideoUrl: VIDEOS.chairTraditional },
  ),
  W(
    "catalog-chair-pull-up",
    "拉升",
    "Pull Up",
    "中高階",
    ["核心", "手臂", "肩膀"],
    ["支撐姿勢"],
    {
      conditions: ["手腕負重", "肩膀負重"],
      demoVideoUrl: VIDEOS.chairTraditional,
    },
  ),
  W(
    "catalog-chair-table",
    "桌式",
    "Table Top",
    "中階",
    ["臀部", "手臂", "核心"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重"] },
  ),
  W(
    "catalog-chair-going-up-front",
    "正面上椅",
    "Going Up Front",
    "中高階",
    ["大腿", "臀部", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"], demoVideoUrl: VIDEOS.chairTraditional },
  ),
  W(
    "catalog-chair-going-up-side",
    "側面上椅",
    "Going Up Side",
    "高階",
    ["大腿", "臀部", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"], demoVideoUrl: VIDEOS.chairTraditional },
  ),
  W(
    "catalog-chair-corkscrew",
    "椅上開瓶器",
    "Chair Corkscrew",
    "高階",
    ["核心", "髖部", "平衡"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "平衡需求"] },
  ),
  W(
    "catalog-chair-one-arm-side",
    "單臂側向下壓",
    "Push Down One Arm Side",
    "中高階",
    ["肩膀", "手臂", "核心"],
    ["站姿"],
    { conditions: ["單側"] },
  ),
  W(
    "catalog-chair-frog-facing",
    "面向椅青蛙",
    "Frog Facing Chair",
    "中階",
    ["核心", "大腿", "手臂"],
    ["支撐姿勢"],
    { conditions: ["手腕負重"] },
  ),
  W(
    "catalog-chair-spine-stretch",
    "椅上脊柱前伸",
    "Spine Stretch Forward",
    "初中階",
    ["背部", "核心", "伸展"],
    ["坐姿"],
  ),
  W(
    "catalog-chair-press-teaser",
    "地板 Teaser 下壓",
    "Press Down Teaser",
    "中階",
    ["核心", "手臂", "髖部"],
    ["坐姿"],
  ),
  W(
    "catalog-chair-frog-facing-out",
    "背向椅青蛙",
    "Frog Facing Out",
    "中高階",
    ["核心", "大腿", "手臂"],
    ["支撐姿勢"],
    { conditions: ["手腕負重"] },
  ),
  W(
    "catalog-chair-pumping",
    "踩踏泵動",
    "Pumping",
    "中階",
    ["大腿", "臀部", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "平衡需求"], demoVideoUrl: VIDEOS.chairTraditional },
  ),
  W(
    "catalog-chair-washer",
    "洗衣女式",
    "Washer Woman",
    "中階",
    ["核心", "背部", "大腿"],
    ["站姿"],
  ),
  W(
    "catalog-chair-leg-press",
    "單腿下壓",
    "Leg Press Down",
    "中階",
    ["大腿", "臀部", "平衡"],
    ["站姿"],
    { conditions: ["單腳", "單側", "平衡需求"] },
  ),
];

const barrelSeeds: Seed[] = [
  B(
    "catalog-barrel-ballet-front",
    "芭蕾腿伸展－前側",
    "Ballet Stretch: Front",
    "初階",
    ["大腿", "髖部", "伸展"],
    ["站姿"],
    { conditions: ["單腳", "單側"] },
  ),
  B(
    "catalog-barrel-ballet-front-bent",
    "芭蕾腿伸展－前側屈膝",
    "Ballet Stretch: Front Bent Leg",
    "初中階",
    ["大腿", "髖部", "伸展"],
    ["站姿"],
    { conditions: ["單腳", "單側"] },
  ),
  B(
    "catalog-barrel-ballet-side",
    "芭蕾腿伸展－側向",
    "Ballet Stretch: Side",
    "初中階",
    ["髖部", "大腿", "伸展"],
    ["站姿"],
    { conditions: ["單腳", "單側", "平衡需求"] },
  ),
  B(
    "catalog-barrel-ballet-back",
    "芭蕾腿伸展－後側",
    "Ballet Stretch: Back",
    "中階",
    ["髖部", "大腿", "伸展"],
    ["站姿"],
    { conditions: ["單腳", "單側", "平衡需求"] },
  ),
  B(
    "catalog-barrel-swan",
    "梯桶天鵝",
    "Ladder Barrel Swan",
    "中階",
    ["背部", "臀部", "全身"],
    ["趴姿"],
  ),
  B(
    "catalog-barrel-horseback",
    "梯桶騎馬式",
    "Ladder Barrel Horseback",
    "中階",
    ["核心", "大腿", "平衡"],
    ["坐姿"],
  ),
  B(
    "catalog-barrel-backbend",
    "站姿後彎",
    "Standing Backbend",
    "中高階",
    ["背部", "胸部", "伸展"],
    ["站姿"],
    { conditions: ["平衡需求"] },
  ),
  B(
    "catalog-barrel-side-stretch",
    "梯桶側伸展",
    "Side Stretch",
    "初中階",
    ["背部", "髖部", "伸展"],
    ["側躺"],
  ),
  B(
    "catalog-barrel-short-round",
    "梯桶短箱－圓背",
    "Barrel Short Box: Round",
    "初中階",
    ["核心", "背部"],
    ["坐姿"],
  ),
  B(
    "catalog-barrel-short-flat",
    "梯桶短箱－平背",
    "Barrel Short Box: Flat",
    "中階",
    ["核心", "背部", "穩定"],
    ["坐姿"],
  ),
  B(
    "catalog-barrel-short-side",
    "梯桶短箱－側彎",
    "Barrel Short Box: Side to Side",
    "中階",
    ["核心", "背部", "伸展"],
    ["坐姿"],
  ),
  B(
    "catalog-barrel-short-twist",
    "梯桶短箱－旋轉",
    "Barrel Short Box: Twist",
    "中階",
    ["核心", "背部", "穩定"],
    ["坐姿"],
  ),
  B(
    "catalog-barrel-tree",
    "梯桶爬樹",
    "Barrel Short Box: Tree",
    "中階",
    ["核心", "髖部", "伸展"],
    ["坐姿"],
    { conditions: ["單腳", "單側"] },
  ),
  B(
    "catalog-barrel-side-situp",
    "梯桶側仰臥起坐",
    "Side Sit Up",
    "中高階",
    ["核心", "背部", "平衡"],
    ["側躺"],
    { conditions: ["單側", "平衡需求"] },
  ),
  B(
    "catalog-barrel-handstand",
    "梯桶倒立",
    "Ladder Barrel Handstand",
    "高階",
    ["全身", "肩膀", "平衡"],
    ["支撐姿勢"],
    { conditions: ["手腕負重", "肩膀負重", "平衡需求"] },
  ),
];

export const exerciseCatalogSeeds: Seed[] = [
  ...reformerSeeds,
  ...cadillacSeeds,
  ...chairSeeds,
  ...barrelSeeds,
];

function createCatalogExercise(seed: Seed, timestamp: string): Exercise {
  const movementType =
    seed.movementType ??
    (seed.areas.includes("伸展")
      ? "伸展"
      : seed.areas.includes("平衡")
        ? "平衡"
        : "整合");
  const position = seed.positions.join("／") || "適合的位置";
  return {
    id: seed.id,
    nameZh: seed.nameZh,
    nameEn: seed.nameEn,
    aliases: seed.aliases ?? [],
    apparatus: seed.apparatus,
    level: seed.level,
    primaryAreas: seed.areas,
    secondaryAreas: [],
    startPositions: seed.positions,
    movementType,
    suggestedReps: seed.reps ?? "5–8 次",
    suggestedSeconds: seed.seconds ?? 180,
    spring: seed.spring ?? "依器械／學員調整",
    footbar:
      seed.footbar ?? (seed.apparatus === "Reformer" ? "依動作設定" : "不適用"),
    headrest:
      seed.headrest ??
      (seed.apparatus === "Reformer" ? "依動作設定" : "不適用"),
    usesBox: seed.usesBox ?? false,
    description: {
      startPosition: `確認器械安全後，進入${position}的穩定起始位置。`,
      flow:
        seed.descriptionFlow ??
        `以可控制的範圍完成「${seed.nameZh}」，依學生狀況調整阻力、幅度與節奏。`,
      endPosition: "控制器械回到安全位置，再安排下一個動作或換邊。",
    },
    defaultCue: {
      preparation: "先確認彈簧、固定點與器械周邊安全。",
      start: `進入${position}，找到穩定且可呼吸的位置。`,
      breathing: "保持呼吸流動，不因增加難度而憋氣。",
      core: "讓軀幹維持可控制的連結，避免用慣性帶動器械。",
      movement:
        seed.cueMovement ?? `平順完成${seed.nameZh}，去程與回程都保持控制。`,
      correction: "若穩定度下降，先減少幅度、阻力或改用退階版本。",
      finish: "慢慢回到起始位置，確認器械停止後再轉換。",
    },
    breathing: "依老師培訓系統與動作目的安排呼吸。",
    commonErrors: "速度過快、失去器械控制，或為追求幅度而出現代償。",
    corrections: "降低幅度與速度，重新確認支撐點、呼吸及器械設定。",
    cautions:
      "內建內容僅供教師備課與回想；請依培訓系統、器械品牌及學生當日狀況調整。",
    contraindications: "需由合格教師依個別狀況評估，不作為醫療判斷。",
    regression: seed.regression ?? "減少動作幅度、降低複雜度，或增加器械支撐。",
    progression:
      seed.progression ?? "在維持控制下加入單側、平衡、節奏或完整動作變化。",
    alternatives: [],
    prerequisites: [],
    suggestedNext: [],
    personalNote:
      seed.personalNote ??
      "市場動作目錄示範資料；中文名稱、Cue 與設定都可自行修改。",
    specialConditions: seed.conditions ?? [],
    sourceUrl: seed.sourceUrl,
    demoVideoUrl: seed.demoVideoUrl,
    isFavorite: false,
    isCustom: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

export function createExerciseCatalog(timestamp: string): Exercise[] {
  return exerciseCatalogSeeds.map((seed) =>
    createCatalogExercise(seed, timestamp),
  );
}

export function mergeExerciseCatalog(
  exercises: Exercise[],
  timestamp: string,
): Exercise[] {
  const catalog = createExerciseCatalog(timestamp);
  const catalogById = new Map(
    catalog.map((exercise) => [exercise.id, exercise]),
  );
  const existingIds = new Set(exercises.map((exercise) => exercise.id));
  const enhanced = exercises.map((exercise) => {
    const builtIn = catalogById.get(exercise.id);
    if (!builtIn || exercise.isCustom) return exercise;
    return {
      ...exercise,
      sourceUrl: exercise.sourceUrl ?? builtIn.sourceUrl,
      demoVideoUrl: exercise.demoVideoUrl ?? builtIn.demoVideoUrl,
    };
  });
  return [
    ...enhanced,
    ...catalog.filter((exercise) => !existingIds.has(exercise.id)),
  ];
}

export function dataNeedsExerciseCatalogMigration(data: AppData): boolean {
  return data.settings.exerciseCatalogVersion < EXERCISE_CATALOG_VERSION;
}

export function migrateExerciseCatalog(data: AppData): AppData {
  if (!dataNeedsExerciseCatalogMigration(data)) return data;
  return {
    ...data,
    exercises: mergeExerciseCatalog(data.exercises, new Date().toISOString()),
    settings: {
      ...data.settings,
      exerciseCatalogVersion: EXERCISE_CATALOG_VERSION,
    },
  };
}
